# geneSetEnrichment_PerturbationScore_Randolph2021_IAV.R

## GENESET ENRICHEMENT ANALYSIS BASED ON THE CORRELATION OF:
## PERTURBATION SCORE AND GENE EXPRESSION


# bsub -Is -XF -m cn003 -R 'rusage[mem=5000]' -n 4 /bin/bash
# conda activate newENv

## TO RUN: 
# Rscript geneSetEnrichment_PerturbationScore_Randolph2021_IAV.R > geneSetEnrichment_PerturbationScore_Randolph2021_IAV_log.txt 2>&1


## Load libraries
library(singlecellmethods)
library(harmony)
library(plyr) #
library(dplyr)
library(tidyr)
library(fgsea)
library(GSA)
library(pheatmap)
library(ggplot2)
library(patchwork)
library(ggrastr)
theme_set(theme_classic())
source('~/10x_Multiome_GEaTac/10x_PBMC/Rfunctions.R')
options(stringsAsFactors=FALSE)

## Create directory for ANALYSIS
main_dir <- '/path_to_directory'
sub_dir <- 'geneSetEnrichment'
output.dir <- file.path(main_dir,sub_dir)
if(!dir.exists(output.dir)){
dir.create(output.dir) 
} else{
	print('Directory already exist')
}

files.path <- paste0(output.dir,'/')
files.data <- '/path_to_directory/'


 
## DATA ge_counts mrnaNorm meta.data
load("/path_to_directory/Randolph2021_PBMC_Clean.Rda") # 
rm(pca_mrnaScaled);gc() #  Keep 

## CELLTYPES
celltypes <- c('B', 'CD4_T', 'CD8_T', 'monocytes', 'NK')

## FILTER DATA 202035 cells
## Select cell from ge_counts, meta.data
meta.data <- meta.data[meta.data$celltype %in% celltypes, ]
meta.data <- meta.data[meta.data$SOC_indiv_ID != "HMN52545",] # 199,879 cells 


## Keep cells that pass QC
ge_counts <- ge_counts[,row.names(meta.data)] # 19248 202035

## DEFINE VARIABLE GENES
var_genes <- singlecellmethods::vargenes_vst(object = ge_counts, topn = 3000) #

## SCALE DATA (MOST VARIABLE GENES)
mrnaNorm <- mrnaNorm[, row.names(meta.data)]
mrnaCosScaled <- mrnaNorm[rownames(mrnaNorm) %in% var_genes, ] %>% scaleData() %>% cosine_normalize(2)


## OPEN PERTURBATION SCORE
lda <- readRDS(paste0(files.data,'PerturbationScore_Randolph2021_IAV.rds')) #

meta.data$lda <- lda[row.names(meta.data),'s0']
rm(lda); gc()

## PERTURBATION SCORE AS VECTOR
lda <- meta.data$lda


## Correlation gene expression with lda loadings
corrs <- cor(t(as.matrix(mrnaCosScaled)),lda ) # data.frame

genes <- as.list(var_genes)

corrs.sig <- lapply(genes,function(i) {
	my_expr = mrnaCosScaled[match(i, rownames(mrnaCosScaled)),]
    my_data = data.frame(lda, my_expr)
    colnames(my_data) = c("lda", "expr")
    new_summary = summary(lm(lda ~ expr, data = my_data))
    new_p = new_summary$coefficients[2,4] %>% format(scientific=TRUE,digits=3)
    return(new_p)
} )
names(corrs.sig) <- var_genes

corrs.df <- ldply(corrs.sig,data.frame)
colnames(corrs.df) <- c('gene','p')
corrs <- data.frame(gene = row.names(corrs), corrs)

## MERGE
corrs.df <- merge(corrs,corrs.df,by='gene')

## APPLY FDR (q<0.05)
corrs.df$p <- as.numeric(corrs.df$p)
corrs.df$pQ <- qvalue::qvalue(corrs.df$p)$qvalue
corrs.df$pQ <- as.numeric(corrs.df$pQ)
corrs.df <- corrs.df[corrs.df$pQ<0.05,] # 
## SAVE FILE
saveRDS(corrs.df,file=paste0(files.path,'corr_PerturbationScore_EXP_Randolph2021_IAV.rds'))


## ORDER BY CORR
corrs.df <- corrs.df[order(corrs.df$corrs,decreasing=TRUE), ]

ranklist <- corrs.df$corrs
names(ranklist) <- corrs.df$gene

# (H): Hallmark gene sets summarize and represent specific well-defined biological states or processes and display coherent expression. 
# These gene sets were generated by a computational methodology based on identifying overlaps between gene sets in other MSigDB collections 
# and retaining genes that display coordinate expression

## DEFINE GENE SETS
geneset_files = c("/path_to_directory/MSigDB_Sets/h.all.v2023.2.Hs.symbols.gmt.txt") 

## THRESHOLDS
GeneSet_SizeBound_Upper = 500 # Maximum gene set size considered
GeneSet_SizeBound_Lower = 0 # Minimum gene set size considered

## FUNCTION TO SELECT GENE SETS 
parseGeneSetGMT <-function(filepath, known_genes, sizeBound_Upper, sizeBound_Lower){
  Gene_Sets_DB = GSA.read.gmt(filepath)
  GeneSet_sizes = sapply(Gene_Sets_DB$genesets,length)
  recognized_genes = matrix(NA, nrow=length(GeneSet_sizes), ncol = max(GeneSet_sizes))
  for(i in c(1:length(GeneSet_sizes))){
    recognized_genes[i,c(1:GeneSet_sizes[i])] = Gene_Sets_DB$genesets[[i]]
  }
  recognized_genes = matrix(is.element(recognized_genes, known_genes), ncol = ncol(recognized_genes))
  GeneSet_sizes = apply(recognized_genes, 1, sum)
  retain_GeneSet = (GeneSet_sizes>=sizeBound_Lower)&(GeneSet_sizes<=sizeBound_Upper)
  Gene_Sets_DB$genesets = Gene_Sets_DB$genesets[retain_GeneSet]
  Gene_Sets_DB$geneset.names = Gene_Sets_DB$geneset.names[retain_GeneSet]
  Gene_Sets_DB$geneset.descriptions = Gene_Sets_DB$geneset.descriptions[retain_GeneSet]
  Gene_Sets_DB$geneset.sizes = GeneSet_sizes[retain_GeneSet]
  return(Gene_Sets_DB)
}
## SELECT GENE SETS : geneset_files[1]
Gene_Sets_DB = parseGeneSetGMT(geneset_files[1], names(ranklist), GeneSet_SizeBound_Upper,
                               GeneSet_SizeBound_Lower)

input_genesets = Gene_Sets_DB$genesets
names(input_genesets) = Gene_Sets_DB$geneset.names

## GENE ENRICHMENT 
FGSEA_output = fgsea(input_genesets, ranklist, nperm=10000, 
                         minSize = 0, maxSize = 500, nproc = 0,
                         gseaParam = 1, BPPARAM = NULL)

FGSEA_output <-  FGSEA_output[order(FGSEA_output$padj),] #  

# SELECT BASED ON PADJ<0.05
FGSEA_output_sig <- FGSEA_output[which(FGSEA_output$padj<0.05),] 

## SAVE RESULTS
saveRDS(FGSEA_output_sig,file=paste0(files.path,'geneSetEnrichment_PerturbationScore_Randolph2021_IAV.rds'))


## Reproducibility info
print('Reproducibility Information:')
Sys.time()
proc.time()
devtools::session_info()